// <auto-generated />
namespace Judgmentrac.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UserProfileJudgmentIndentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserProfileJudgmentIndentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201209201603145_UserProfileJudgmentIndentity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
